Refactor
tebrex1995/playwrightProject pull request #3
Opened 2024-10-01 14:23 UTC by tebrex1995

2024-10-01 14:52 UTC, fnedovic-ionos commented on POM/modules/ui/loginPage.js
> +    // this.heading = page.locator('h1');
Obrisi zakomentarisanu liniju

2024-10-01 14:52 UTC, fnedovic-ionos commented on POM/modules/ui/registerPage.js
> +    // this.heading = page.locator('h1');
Obrisi zakomentarisanu liniju

2024-10-01 14:52 UTC, fnedovic-ionos commented on POM/modules/ui/registerPage.js
> +    this.successRegisterMessage = page.getByText('Successfully registered!');
Izmesti tekstualnu vrednost iz klase

2024-10-01 14:52 UTC, fnedovic-ionos commented on POM/modules/ui/registerPage.js
> +      hasText: 'Already have an account?',
Isti komentar kao i gore

2024-10-01 14:52 UTC, fnedovic-ionos commented on POM/modules/ui/registerPage.js
> +    //initiate header class
*Instantiate

2024-10-01 14:52 UTC, fnedovic-ionos commented on POM/modules/ui/registerPage.js
> +    await await this.usernameInput.fill(username);
2x await

2024-10-01 14:52 UTC, fnedovic-ionos commented on tests/auth.spec.js
> +    //Initiate register class
*Instantiate

2024-10-01 14:52 UTC, fnedovic-ionos commented on tests/auth.spec.js
> +    //initiate login class
Isti komentar

2024-10-01 14:52 UTC, fnedovic-ionos commented on tests/auth.spec.js
> +    //Login user assertations
Ovom komentaru nije mesto tu

2024-10-03 12:58 UTC, filip-n91 requested changes

2024-10-03 12:58 UTC, filip-n91 commented on POM/modules/api/loginApi.js
> +      `/${URLS['BASE_API']}${URLS['LOGIN']}`,
Login endpoint mozes u konstruktoru da definises.

2024-10-03 12:58 UTC, filip-n91 commented on POM/modules/api/registerApi.js
> +      `${URLS['BASE_API']}${URLS['REGISTER']}`,
Isti komentar kao i za login.

2024-10-03 12:58 UTC, filip-n91 commented on POM/modules/ui/registerPage.js
> +    //Success message
Suvisan komentar.

2024-10-03 12:58 UTC, filip-n91 commented on fixtures/pageTextValues.js
> +  //Register error messages
Napravi podobjekat umesto sto ostavljas komentare u objektu.

2024-10-03 12:58 UTC, filip-n91 commented on fixtures/pages.js
> +  BASE_API: 'api/v1/auth',
BASE_API bi isao kao zasebna konstanta, ne unutar ovog objekta.

2024-10-03 12:58 UTC, filip-n91 commented on fixtures/utils.js
> +};
Ne bi ovo islo u utils, pre napravi neku klasu `Common` npr.

2024-10-03 12:58 UTC, filip-n91 commented on POM/modules/ui/loginPage.js
> +      utils.formInputLocators.loginMissingPassword
Ne bih ipak ovako izmestao lokatore u utils, mesto im je u ovom ili nekom shared POM-u.

2024-10-03 12:58 UTC, filip-n91 commented on tests/auth-api.spec.js
> +  test('NE - Register with all input fields emty', async ({ page }) => {
Typo - `empty`. I mali tip za pisanje test case-ova:
`Shouldn't be able to register without providing data`, da stavljas expected result u opis test case-a.

2024-10-03 12:58 UTC, filip-n91 commented on tests/auth-api.spec.js
> +    //Register user successfully
Copy/paste greska? Necu pisati za sva ponavljanja.

2024-10-03 12:58 UTC, filip-n91 commented on tests/auth-api.spec.js
> +  test('NE - Login with empty input fields', async ({ page }) => {
Razdvoj login i register u dva spec-a.

2024-10-03 12:58 UTC, filip-n91 commented on tests/auth-api.spec.js
> +    const registerApi = new RegisterApi(page);
Klasu mozes da instanciras u before hook-u umesto u svakom testu ponovo.

2024-10-03 15:41 UTC, tebrex1995 commented on fixtures/utils.js
> +};
Zasad sam stavio u register POM-u

2024-10-06 17:21 UTC, filip-n91 requested changes

2024-10-06 17:21 UTC, filip-n91 commented on POM/modules/api/loginApi.js
> +    this.nonExistingUser = {
Necemo ovo stavljati u konstruktor login API-ja, bolje da svi testni podaci idu u fixtures folder

2024-10-06 17:21 UTC, filip-n91 commented on POM/modules/api/loginApi.js
> +    this.loginEndpoint = `${BASE_API['BASE_API']}${URLS['LOGIN']}`;
Takodje endpoint izmesti u fixtures, kao sto imas konstantu `URLS` imaces i konstantu `ENDPOINTS`

2024-10-06 17:21 UTC, filip-n91 commented on POM/modules/api/registerApi.js
> +    this.shortPassword = {
Isti komentar za testne podatke kao i za login

2024-10-06 17:21 UTC, filip-n91 commented on POM/modules/ui/footer.js
> +}
Refaktorisacemo ovo, neka ostane ovako za sad

2024-10-06 17:21 UTC, filip-n91 commented on POM/modules/ui/loginPage.js
> +    //Test Data
Isti komentar za testne podatke.

2024-10-06 17:21 UTC, filip-n91 commented on tests/login-api.spec.js
> +  test('NE - Shouldn"t be able to login without provided data', async ({
Ostavljaj praznu liniju razmaka izmedju testova

2024-10-06 17:21 UTC, filip-n91 commented on tests/login-api.spec.js
> +  test('Login with registerd user', async ({ page }) => {
Typo - registered

2024-10-06 17:21 UTC, filip-n91 commented on tests/login-api.spec.js
> +  test('NE - Shouldn"t be able to login with not registered user', async ({
Zameni dvostruke i jednostruke navodnike, ili escape-uj apostrof:
`'NE - Shouldn\'t be able to login with not registered user'`

2024-10-06 17:21 UTC, filip-n91 commented on tests/register-api.spec.js
> +  test('Shouldn"t be able to register without provided data', async ({
Isti komentar za navodnike, necu pisati vise na svim ponavljanjima

2024-10-06 17:21 UTC, filip-n91 commented on tests/register-api.spec.js
> +    //Register user successfully
Copy paste greska u komentaru

2024-10-06 17:21 UTC, filip-n91 commented on tests/register-api.spec.js
> +    //Register user successfully
Isti komentar za copy paste, necu pisati na svim ponavljanjima.

2024-10-07 09:18 UTC, filip-n91 commented on POM/modules/api/loginApi.js
> +    let response = await this.page.request.post(END_POINTS['LOGIN_ENDPOINT'], {
ENDPOINT, jedna rec :) Izmeni to i moze merge

2024-10-07 12:35 UTC, merged